title: E-Tech I&C Main Pages
description: "System Engineering Expert"
author:
  name: "Pil-Jin.Kwon"
  email: "etechinc@naver.com"
  url: "https://e-techinc.github.io/etechinc/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "E-Tech I&C,.All Rights Reserved"
year : "Since. 2019.10"
